version: '3'
services:
  db:
    image: postgres:latest
    container_name: cogitocovedb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: cogitocove